databases:
  - name: chat_application
    plan: free
    databaseName: chat_application_eu51
    user: ms04

services:
  - type: web
    plan: free
    name: chat_application
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py runserver"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chat_application
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4  

