# Generated by Django 5.0.7 on 2024-08-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.TextField(null=True),
        ),
    ]
